# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Notebook < Formula
  desc "A terminal-native note editor with a block-based editing experience"
  homepage "https://github.com/oobagi/notebook-cli"
  version "1.5.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oobagi/notebook-cli/releases/download/v1.5.5/notebook-cli_1.5.5_darwin_amd64.tar.gz"
      sha256 "2714529a2e8ed6d305422ee16b972da8e1af4c6a6418f2494c47857fb9a73d6b"

      define_method(:install) do
        bin.install "notebook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oobagi/notebook-cli/releases/download/v1.5.5/notebook-cli_1.5.5_darwin_arm64.tar.gz"
      sha256 "74ed304801039217653c9422cc68742c93d9e63f68f7b44cf44c8e1900a3207b"

      define_method(:install) do
        bin.install "notebook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oobagi/notebook-cli/releases/download/v1.5.5/notebook-cli_1.5.5_linux_amd64.tar.gz"
      sha256 "2a9aff3d297953ee8cd7fcd0f48de65ec94d51eb3395b7fa3cf4cdb3dbdc9e73"
      define_method(:install) do
        bin.install "notebook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oobagi/notebook-cli/releases/download/v1.5.5/notebook-cli_1.5.5_linux_arm64.tar.gz"
      sha256 "916b15a15e6408cfa7fa47215f2603ce7c3ca7e3f2b9ca8926ee89554af74ebe"
      define_method(:install) do
        bin.install "notebook"
      end
    end
  end
end
