# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Notebook < Formula
  desc "A terminal-native note editor with a block-based editing experience"
  homepage "https://github.com/oobagi/notebook-cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oobagi/notebook-cli/releases/download/v1.0.0/notebook-cli_1.0.0_darwin_amd64.tar.gz"
      sha256 "39ec06c03dd462431807a08b96f73a80a77157c8d4ef57a1b2c26042611c276e"

      define_method(:install) do
        bin.install "notebook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oobagi/notebook-cli/releases/download/v1.0.0/notebook-cli_1.0.0_darwin_arm64.tar.gz"
      sha256 "9ebaa3adafbad0fb4fe86cda44c853f2fac82f7b817f33e3191890b58710f248"

      define_method(:install) do
        bin.install "notebook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oobagi/notebook-cli/releases/download/v1.0.0/notebook-cli_1.0.0_linux_amd64.tar.gz"
      sha256 "78339bccbc2e2feb1e44450ed75e03b9a97d02ac3bf88ad002e6a60f0bcfc5ff"
      define_method(:install) do
        bin.install "notebook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oobagi/notebook-cli/releases/download/v1.0.0/notebook-cli_1.0.0_linux_arm64.tar.gz"
      sha256 "09e643dc68b82b5198966327d1aa0e24b189a485d0f0b56c4056c2f72db79ae6"
      define_method(:install) do
        bin.install "notebook"
      end
    end
  end
end
