# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RecycleCli < Formula
  desc "Safe rm replacement for macOS — moves files to Trash instead of deleting them"
  homepage "https://github.com/oobagi/recycle-cli"
  version "2.0.0"
  license "MIT"
  depends_on :macos

  url "https://github.com/oobagi/recycle-cli/releases/download/v2.0.0/recycle-cli_2.0.0_darwin_all.tar.gz"
  sha256 "8b73dd4b7e9f1556696038ad3e61477d0767b45f0622f145d1069e60cbac687f"

  define_method(:install) do
    bin.install "recycle"
  end

  test do
    system "#{bin}/recycle", "--version"
  end
end
