# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RecycleCli < Formula
  desc "Safe rm replacement for macOS — moves files to Trash instead of deleting them"
  homepage "https://github.com/oobagi/recycle-cli"
  version "2.0.0"
  license "MIT"
  depends_on :macos

  url "https://github.com/oobagi/recycle-cli/releases/download/v2.0.0/recycle-cli_2.0.0_darwin_all.tar.gz"
  sha256 "4bb424fccf43893bc44c52895d6078d3505e96b241299443fb6b39b039a58aa1"

  define_method(:install) do
    bin.install "recycle"
  end

  test do
    system "#{bin}/recycle", "--version"
  end
end
